### ISSUE TITLE
using tag uri scheme for queue and exchange names are not longer possible

### ISSUE THREAD

**Issue by deschmih** [mosquito/aiormq#143]
Hi,
I'm using your aiormq indirectly with aio-pika. Since an update of pamqp (v3.1.0) in setup.py, I got some errors. This errors are based on DOMAIN_REGEX in lib pamqp (v3.1.0), because I'm using tag uri sheme ([tag URI scheme - Wikipedia](https://en.wikipedia.org/wiki/Tag_URI_scheme)) ([tag URI scheme - IETF](https://www.ietf.org/rfc/rfc4151.txt)) for naming queue and exchanges.

see also:
https://github.com/gmr/pamqp/issues/41

This issue [gmr/pamqp](https://github.com/gmr/pamqp/issues/41) is now fixed in pamqp version v3.2.0. It would be really nice to reference the latest version in setup.py.

https://github.com/mosquito/aiormq/blob/ded8f83644963d93a94c0653c07d431d6ff50a67/setup.py#L23

Kind regards,
Michael

**Comment by mosquito** [comment]
So, could you please create a PR with bump this version, the tests should check the version compatibility.

**Comment by mosquito** [comment]
Released as aiormq==6.3.4
