### ISSUE TITLE
`basic_publish` holds a lock until the message is confirmed

### ISSUE THREAD

**Issue by Tasssadar** [mosquito/aiormq#146]
Hello, `channel.basic_publish` seems to be holding a channel lock until the message is fully confirmed, resulting in serialization of concurrent `basic_publish` calls.

```python
async with countdown.enter_context(self.lock):
            self.delivery_tag += 1

            if self.publisher_confirms:
                message_id = content_header.properties.message_id

                if self.delivery_tag not in self.confirmations:
                    self.confirmations[
                        self.delivery_tag
                    ] = self.create_future()

                confirmation = self.confirmations[self.delivery_tag]
                self.message_id_delivery_tag[message_id] = self.delivery_tag

                if confirmation is None:
                    return

                confirmation.add_done_callback(
                    lambda _: self.message_id_delivery_tag.pop(
                        message_id, None,
                    ),
                )

            body_frames: List[Union[FrameType, ContentBody]]
            body_frames = [publish_frame, content_header]
            body_frames += self._split_body(body)

            await countdown(
                self.write_queue.put(
                    ChannelFrame(
                        frames=body_frames,
                        channel_number=self.number,
                        drain_future=drain_future,
                    ),
                ),
            )

            if drain_future:
                await drain_future

            if not self.publisher_confirms:
                return None

            if confirmation is None:
                return None

            return await countdown(confirmation)
```

It seems to me that the rest of the code is pretty much ready for concurrent confirmations, perhaps the last `return` line should just be one level less indented?

**Comment by gonzalesMK** [comment]
@Tasssadar , would you mind to point me out why there is a need for the lock at all in the basic_publish ?

**Comment by mosquito** [comment]
@Tasssadar just disable publisher confirms to avoid this

**Comment by Tasssadar** [comment]
I want the confirms though, they serve a purpose after all. Plus, aio-pika has them on by default.

Can you just check if it isn't holding the lock by mistake? It could be a simple fix with huge impact, but I don't know enough about architecture of this library to be sure.

**Comment by mosquito** [comment]
tell us more, did you notice blocking in aio-pika or aiormq?  I'm just trying to figure out where you want to make the fix.

**Comment by Tasssadar** [comment]
We're using aio-pika, and it had strangely low throughput with publisher confirms enabled. The publishing calls with aio-pika do basically nothing, and just call aiormq's `basic_publish` in the end.

To me, it looks like that `self.lock` is held until the RMQ message is confirmed by the server, so you can't ever have more than one message in flight on one channel, which is not great. At the same time, to me, it looks like the library is ready to work with multiple messages in flight and confirm them concurrently, if only the `return await countdown(confirmation)` statement were outside the `async with` block.

**Comment by jwldk** [comment]
We have experienced something similar as well. Enabling publisher confirms had a pretty big performance impact. Our current workaround is to have 10 channels for publishing which we switch around in a round-robin fashion. I don't have exact numbers from a performance test right now but it made a difference.

**Comment by mosquito** [comment]
Good practice, from my point of view, is to use transactions, for example every 1000 messages. I don't remember if there are any restrictions in the protocol for waiting for publisher confirms.

**Comment by Tasssadar** [comment]
Transaction have a bit different semantics, and are much more expensive - [around 250x when compared to publisher confirms](https://www.rabbitmq.com/confirms.html#publisher-confirms).

We're using big batches with RMQ in other apps - sending ~500 messages and only waiting for confirms after that. [The docs](https://www.rabbitmq.com/confirms.html#publisher-confirms-latency) say that's the way to go:
> ...To improve throughput, applications are strongly advised to process acknowledgements asynchronously (as a stream) or publish batches of messages and wait for outstanding confirms. The exact API for this varies between client libraries....

**Comment by mosquito** [comment]
@Tasssadar could you please check the [beta version with the fix](https://pypi.org/project/aiormq/6.4.1b0/)

**Comment by Tasssadar** [comment]
I unfortunately don't have a service a hand to easily tests this, but I have written a short script that just publishes on multiple tasks.

`aio-pika==8.1.1`, `aiormq==**6.4.0**`, publishing 10k messages on **10 tasks**
> Took 203.274297s to publish 10000 messages, 20.327430 ms/msg, **49.194611 msgs/s**

`aio-pika==8.1.1`, `aiormq==**6.4.1b0**`, publishing 10k messages on **10 tasks**
> Took 18.421677s to publish 10000 messages, 1.842168 ms/msg, **542.838741 msgs/s**

`aio-pika==8.1.1`, `aiormq==**6.4.1b0**`, publishing 100k messages on **100 tasks**
> Took 29.382919s to publish 100000 messages, 0.293829 ms/msg, **3403.337842 msgs/s**

Let me also note that CPU was barely used with 6.4.0 as opposed to ~50% with 6.4.1b0.


**RMQ management graphs**, the barely visible increase at the start is the old 6.4.0, the small peak is the beta with 10 tasks, the large one is beta with 100 tasks:
![image](https://user-images.githubusercontent.com/120108/184131616-e59d5efc-55eb-41ff-b253-48a3e28962e3.png)

Script:
```python
import aio_pika
import asyncio
import uuid
import time
import json

TASKS = 100
MSG_PER_TASK = 100

async def publish(ex: aio_pika.abc.AbstractExchange) -> None:
    for _ in range(MSG_PER_TASK):
        msg = aio_pika.Message(json.dumps({
            "uuid": str(uuid.uuid4()),
        }).encode("utf-8"), delivery_mode=aio_pika.DeliveryMode.PERSISTENT)
        await ex.publish(msg, "test.test")


async def main() -> None:
    connection = await aio_pika.connect_robust(
        "...",
    )

    async with connection:
        chan = await connection.channel()
        ex = await chan.declare_exchange("chadron.test.aiormq", type=aio_pika.ExchangeType.TOPIC, durable=False, auto_delete=True)

        queue = await chan.declare_queue("chadron.test.aiormq", durable=True)
        await queue.bind(ex, "#")


        start = time.monotonic()
        await asyncio.wait([ asyncio.create_task(publish(ex)) for _ in range(TASKS) ])
        dur = time.monotonic() - start
        print("Took %fs to publish %d messages, %f ms/msg, %f msgs/s" % (dur, TASKS*MSG_PER_TASK, dur/(TASKS*MSG_PER_TASK)*1000, (TASKS*MSG_PER_TASK)/dur))


asyncio.run(main())
```

**Comment by jwldk** [comment]
Thanks. I can confirm similar results in our smaller scale tests.

**Comment by mosquito** [comment]
@Tasssadar many thanks for this research and your contribution.

**Comment by mosquito** [comment]
A new release available now https://pypi.org/project/aiormq/6.4.1/
