### ISSUE TITLE
Status outdated

### ISSUE THREAD

**Issue by p-baum** [mosquito/aiormq#151]
The status is given as:

    3.x.x branch - Production/Stable
    4.x.x branch - Unstable (Experimental)

Is this up to date?  Where do versions 5 and 6 stand?  To take version 3 for production is quite a step back from version 6.

**Comment by mosquito** [comment]
Each [release](https://pypi.org/project/aiormq/) contains their own status tag. In the readme.md it's actually redundant, but still here.
<img width="556" alt="image" src="https://user-images.githubusercontent.com/792981/192556781-fe226df7-0195-4c41-a0aa-177431743d5d.png">
