### ISSUE TITLE
AssertionError when drain is called

### ISSUE THREAD

**Issue by decaz** [mosquito/aiormq#17]
I have the following dependencies:
- CPython 3.6.7
- aio-pika==5.4.0
- aiormq==2.1.0

At my service I have loop exception handler (https://docs.python.org/3.6/library/asyncio-eventloop.html#asyncio.AbstractEventLoop.set_exception_handler) therefore I see that after upgrading aio-pika (from version 4 to 5) there are many `AssertionError` appeared inside the `asyncio`:
```
AssertionError: null
  File "asyncio/streams.py", line 339, in drain
    yield from self._protocol._drain_helper()
  File "asyncio/streams.py", line 214, in _drain_helper
    assert waiter is None or waiter.cancelled()
```
I see there are several calls of `asyncio.StreamWriter.drain` within `aiormq.Channel` class (`basic_ack`, `basic_nack` and `basic_reject` methods) so I guess the problem relates to the `aiormq`. Also I guess it may be related to https://bugs.python.org/issue29930.

It's rather difficult to pick the script to reproduce the problem out of the service where it is observed and for this time I just leave it as is here so someone who experiencing the same problem could find this issue.

@mosquito FYI.

**Comment by mosquito** [comment]
Fixed in `aiormq==2.1.1`
