### ISSUE TITLE
Exception within LazyCoroutine

### ISSUE THREAD

**Issue by decaz** [mosquito/aiormq#22]
@mosquito I've already [reported](https://github.com/mosquito/aiormq/commit/3b6d5cc10e485203b2214761a136d87e59cbe3d0#r32892210) about this exception at commit but just in case here is the issue when using Python 3.6:
```
AttributeError: 'coroutine' object has no attribute '__iter__'
  File "service.py", line 444, in ack
    await message.ack()
  File "asyncio/tasks.py", line 537, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "aiormq/tools.py", line 50, in __await__
    return (yield from self().__iter__())
```
The same with synchronous call without `await`.

**Comment by mosquito** [comment]
Please provide full python version. CI tests was fine.

**Comment by decaz** [comment]
CPython 3.6.7

**Comment by mosquito** [comment]
Release `aiormq==2.3.1` has runtime check for avoid this.
