### ISSUE TITLE
tools.py error: RuntimeWarning: coroutine '_test' was never awaited

### ISSUE THREAD

**Issue by gtmartem** [mosquito/aiormq#24]
Hello!
I think, there's a little mistake, but I dont sure.
Thank you for your attention!

[file tools.py, 28 line:](https://github.com/mosquito/aiormq/blob/master/aiormq/tools.py)
`HAS_AWAIT_METHOD = hasattr(_test(), '__await__')`
[Problem is in this merge](https://github.com/mosquito/aiormq/commit/2b8a2c012a73378632a39253bd4665cb1a219dc8)

```
/usr/local/lib/python3.6/site-packages/aiormq/tools.py:28: RuntimeWarning: coroutine '_test' was never awaited
    HAS_AWAIT_METHOD = hasattr(_test(), '__await__')
```

**Comment by mosquito** [comment]
Fixed in `aiormq==2.3.3`
