### ISSUE TITLE
[2.5.5] Repeated KeyError when manually acking

### ISSUE THREAD

**Issue by gregdan3** [mosquito/aiormq#42]
In channels.Channel._confirm_delivery():
```    def _confirm_delivery(self, delivery_tag, frame: ConfirmationFrameType):
        confirmation = self.confirmations.pop(delivery_tag)

        if confirmation is self.Returning:
            return
        elif confirmation.done():  # pragma: nocover
            log.warn(
                "Delivery tag %r confirmed %r was ignored",
                delivery_tag, frame
            )
            return
        elif isinstance(frame, spec.Basic.Ack):
            confirmation.set_result(frame)
            return

        confirmation.set_exception(
            exc.DeliveryError(None, frame)
        )  # pragma: nocover
```

I get the following errors on each attempt to ack the message (doing so manually):

```

[2019-06-21 13:00:31,912] [        base_events.py:1268] [   ERROR]   Exception in callback Channel._confirm_delivery(7542, <pamqp.specif...0x2480e5a49b0>)
handle: <Handle Channel._confirm_delivery(7542, <pamqp.specif...0x2480e5a49b0>)>
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "C:\Users\gregdan3\AppData\Roaming\Python\Python36\site-packages\aiormq\channel.py", line 200, in _confirm_delivery
    confirmation = self.confirmations.pop(delivery_tag)
KeyError: 7542

[2019-06-21 13:00:31,912] [        base_events.py:1268] [   ERROR]   Exception in callback Channel._confirm_delivery(7543, <pamqp.specif...0x2480e5a49b0>)
handle: <Handle Channel._confirm_delivery(7543, <pamqp.specif...0x2480e5a49b0>)>
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "C:\Users\gregdan3\AppData\Roaming\Python\Python36\site-packages\aiormq\channel.py", line 200, in _confirm_delivery
    confirmation = self.confirmations.pop(delivery_tag)
KeyError: 7543
```

This does not occur in 2.5.3, which is my band-aid solution for the time being.

This is also being run on python 3.6.6, in Windows, if this is relevant. I have demonstrated the problem occurring on other systems (Linux running 3.7.3), as well.

**Comment by mosquito** [comment]
I wish avoid this case, but it's abnormal behaviour. Could you please provide traffic dumps using wireshark with "port 5672" capture filter?

**Comment by mosquito** [comment]
@khvn26 looks like this not related but another interested case.

**Comment by mosquito** [comment]
#43 was closed and 2.5.6 already released. But I still not know why confirmation was duplicated `¯\_(ツ)_/¯`

**Comment by gregdan3** [comment]
[raw_out.txt](https://github.com/mosquito/aiormq/files/3316113/raw_out.txt)
Here is the human-readable output of tshark. I anonymized some of the content. I could not directly upload the .pcap file I had captured before, so let me know if this is not enough and I will find a workaround.

**Comment by gregdan3** [comment]
[rabbit.txt](https://github.com/mosquito/aiormq/files/3321846/rabbit.txt)

Here's the complete traffic capture with some stub methods, being run on 2.5.5.

**Comment by gregdan3** [comment]
Update: The issue still exists in 2.6.0, of course now ignoring duplicate delivery tags instead of failing.

I did discover that, if you intentionally set up the process such that you only receive one work item simultaneously, delivery tags are not duplicated.

This is a very long pcap, but unfortunately I could not reproduce the issue in a shorter instance.

[rabbit.txt](https://github.com/mosquito/aiormq/files/3340276/rabbit.txt)

That is the new capture.

**Comment by mosquito** [comment]
@gregdan3 good news. I will release a beta version of aiormq with fix. Could you test it on your environment?

**Comment by mosquito** [comment]
Released. You could install it with:
```bash
pip install --pre 'aiormq==2.6.1b0'
```

**Comment by gregdan3** [comment]
Still experiencing the same issue. Here is another capture, gathered a few minutes ago on 2.6.1b0

[rabbit.txt](https://github.com/mosquito/aiormq/files/3346578/rabbit.txt)

Large numbers of ignored delivery tags, usually in bursts.
Still does not occur if all items are worked one at a time, but fails as soon as more than one tag is involved.

**Comment by khvn26** [comment]
Check this out:

`AttributeError: 'object' object has no attribute 'done'
  File "uvloop/cbhandles.pyx", line 68, in uvloop.loop.Handle._run
  File "aiormq/channel.py", line 202, in _confirm_delivery
    if confirmation is None or confirmation.done():  # pragma: nocover
`

Looks like the culprit is [here](https://github.com/mosquito/aiormq/blob/master/aiormq/channel.py#L205) - you probably need to check for `Returning` first, then expect a future.

**Comment by gregdan3** [comment]
This is still occuring in aiormq==2.6.1beta2, and aio_pika==2.6.0

I made a script, as minimal as I can achieve within my use-case, demonstrating the issue. It is attached.

[crawl.txt](https://github.com/mosquito/aiormq/files/3452857/crawl.txt)

**Comment by mosquito** [comment]
#50 fixing your example.

**Comment by mosquito** [comment]
It's was redundant logging, when `multiple` flag has been set.
