### ISSUE TITLE
hidden error in Connection._on_close

### ISSUE THREAD

**Issue by alpo** [mosquito/aiormq#46]
I tried to subclass Connection to extend network failures processing.

```
class SomeClass(aiormq.Connection):
    async def _on_close(self, exc=ConnectionClosed(0, 'normal closed')):
        await super()._on_close(exc)
        # rest of the code
```
The "rest of the code" does not execute. After temporary removing of the line https://github.com/mosquito/aiormq/blob/master/aiormq/base.py#L142
I figured out that aiormq.Connection._on_close always fails in the line https://github.com/mosquito/aiormq/blob/master/aiormq/connection.py#L399
due to reason `AttributeError: 'StreamWriter' object has no attribute 'wait_closed'`.

Python 3.6.8
Linux
aiormq 2.6.0

**Comment by coroa** [comment]
`wait_closed` has been introduced in Python 3.7 (see [docs](https://docs.python.org/3/library/asyncio-stream.html#asyncio.StreamWriter.wait_closed)).

So, I suppose the minimum python requirement should be updated.

**Comment by decaz** [comment]
I see @mosquito fixed it at https://github.com/mosquito/aiormq/commit/41fa06dd87015c738dbd909bf6c2d2ff6ba9621f (2.7.5). @alpo can it be closed now?
