### ISSUE TITLE
Protect RPC from cancellation

### ISSUE THREAD

**Issue by decaz** [mosquito/aiormq#55]
If `Channel.rpc` task will be cancelled and `asyncio.CancelledError` will be raised after request frame was written and before response frame was got from `Channel.rpc_frames` queue
https://github.com/mosquito/aiormq/blob/287bb062e0992753c034ba75b68b5be5c7b1daf3/aiormq/channel.py#L84-L98
then `Channel.rpc_frames` queue will be corrupted and next frames will lead to `InvalidFrameError` be raised.

I think `asyncio.Lock` is not enough, but `asyncio.shield` also needed to protect `Channel.rpc` method. Maybe it should be added not only for `Channel.rpc` method but also in some other places. @mosquito what do you think?

**Comment by mosquito** [comment]
See #56

**Comment by decaz** [comment]
@mosquito thanks!
