### ISSUE TITLE
Trying to publish on a closed channel results in broad exception type `RuntimeError`

### ISSUE THREAD

**Issue by phijor** [mosquito/aiormq#63]
Hi,

we are working on an application that, through `aio-pika`, uses `aiormq`.  While dealing with some issues caused by unreliable network conditions, we noticed that trying to publish on a channel that has been closed results in a rather broad `RuntimeError`, raised here:

https://github.com/mosquito/aiormq/blob/5e735e0a5c4d3ac12d5c22bbb811c02cb10a6ee9/aiormq/channel.py#L77

Below is a typical stack trace for when this happens, starting at a call to `aio_pika.Exchange.publish()`:

```
Traceback (most recent call last):
  <snip>
  ...
  </snip>
  File "/<our_project>/source.py", line 106, in _send
    await self.data_exchange.publish(msg, routing_key=metric, mandatory=False)
  File "/<venv>/lib/python3.7/site-packages/aio_pika/exchange.py", line 200, in publish
    ), timeout=timeout
  File "/usr/lib64/python3.7/asyncio/tasks.py", line 414, in wait_for
    return await fut
  File "/<venv>/lib/python3.7/site-packages/aiormq/channel.py", line 426, in basic_publish
    async with self.lock:
  File "/<venv>/lib/python3.7/site-packages/aiormq/channel.py", line 77, in lock
    raise RuntimeError('%r closed' % self)
RuntimeError: <Channel: "1"> closed
```

We are afraid that, when writing error handling code for this condition, catching `RuntimeError` might accidentally catch other errors, too.

Would it be possible to raise a more descriptive exception, of distinct type?  The exception type might subclass `RuntimeError` as to not break code that catches that.

**Comment by decaz** [comment]
Also thought about it. Perhaps existing `ChannelClosed` exception would fit..

**Comment by mosquito** [comment]
Fixed in #65. and `aiormq==3.1.0`

**Comment by mosquito** [comment]
Thank you for this issue and sorry for the delayed reply. I hope I released what are you wanted :-)

Please close this issue if this enough.

**Comment by decaz** [comment]
I remember about need of backward compatibility, but if inherit new exception from `AMQPChannelError` then it would be possible to easily catch any exception raised by aiormq by simply handling `AMQPError`.

**Comment by phijor** [comment]
I like @decaz's idea of having a single exception to catch, but right now having `ChannelInvalidStateError` is good enough, as it cover most (all?) of our use cases.

Thank you :)

Now the only thing that is needed is a release of `aio-pika` that includes this fix. I see that since https://github.com/mosquito/aio-pika/commit/64985751afae608344bbc06c85e7a17f796e2d09, it already uses `aiormq~=3.0`.
