### ISSUE TITLE
[Question] What are the differences between aiormq and aio-pika?

### ISSUE THREAD

**Issue by ElPapi42** [mosquito/aiormq#95]
I don't found the answer to this question on the internet, so decided to ask here!

**Comment by mosquito** [comment]
aiormq is just amqp 0.9.0 client implementation but aio-pika is wrapper around aiormq with more user friendly API and useful abilities e.g. autoreconnects and patterns.

**Comment by ElPapi42** [comment]
Thanks! very clear
